### ISSUE TITLE
Make available via Homebrew

### ISSUE THREAD

**Issue by georgeboot** [whilenull/7777-support#11]
Would you guys consider making this package available via Homebrew so Mac folks can install (and update) this package a tod easier?

**Comment by mnapoli** [comment]
Hi, thanks that's a good point (I'm a Mac user as well and agree this would be nice to have).

I'll try to look into how Homebrew works, if you have any specific pointer let me know.

**Comment by georgeboot** [comment]
https://github.com/Homebrew/homebrew-cask/pull/93028

**Comment by mnapoli** [comment]
Thank you! I'll be following up there.

**Comment by georgeboot** [comment]
Now available as a homebrew cask: `brew cask install 7777`
