### ISSUE TITLE
 Error: There is no subnet routing to the internet

### ISSUE THREAD

**Issue by wedgehead92** [whilenull/7777-support#12]
Hey guys, when I run 7777 I get:
`Error: There is no subnet routing to the internet in availability zone eu-west-2b of VPC vpc-522b5e3a.`
Any idea what I need to do?

**Comment by mnapoli** [comment]
Hi @wedgehead92, have a look at #5: I'm guessing you are using the default VPC provided by AWS?

(especially this last comment: https://github.com/whilenull/7777-support/issues/5#issuecomment-733593007)

**Comment by wedgehead92** [comment]
This worked perfectly, thanks a lot for your rapid response!
