### ISSUE TITLE
Ctrl + C on Ubuntu 24.04 LTS Not Working

### ISSUE THREAD

**Issue by alozie-michael** [whilenull/7777-support#57]
After connection to a database is established. It is impossible to close and destroy the connection. `Ctrl + C` does not work in Ubuntu 24.04 LTS, hence the fargate tasks are left running and a new connection starts on a different port with a different fargate task.

![image](https://github.com/whilenull/7777-support/assets/25454365/ec467f1b-1c37-4aa5-a742-b8cf70ada20b)

**Comment by mnapoli** [comment]
Hi, could you detail what you mean by "does not work"? What actually happens?

**Comment by alozie-michael** [comment]
@mnapoli Nothing happens, the terminal doesn't exit. It stays in that running state. 

However, when I use `Ctrl+z`, the terminal exits and shows "Stopped" but the fargate task is still running. See below images.

![image](https://github.com/whilenull/7777-support/assets/25454365/bd45031b-c99d-4051-85d2-6af1b61e9fa0)

![image](https://github.com/whilenull/7777-support/assets/25454365/8ed23627-199e-4787-b64c-6d2c54aa9f44)

**Comment by mnapoli** [comment]
Thanks for the clarification, I'm taking note of this and I'm looking if I can see anything obvious related to Ubuntu (I'm currently using Mac).

Indeed, Ctrl+Z is a keyboard shortcut that let the current process continue running in the background, it's not exactly what you want here, but it can be used as a workaround in the meantime: https://askubuntu.com/a/14215

Press CTRL+Z and then kill the process by job number: `kill %1` or `kill -9 %1`.
