### ISSUE TITLE
Deleted 7777 Cloudformation but still error

### ISSUE THREAD

**Issue by ziming** [whilenull/7777-support#58]
So i followed your advice in another closed issue to uninstall by deleting 7777 Cloudformation and try again but I still get errors.

I have 2 database in the region i want to access. Trying the 1st database give me this error

```bash
Setting up 7777 in the AWS account, this usually takes 30 seconds.
    ResourceNotReady: Resource is not in the state stackCreateComplete
    Code: ResourceNotReady
```

Trying the 2nd database give me this error

```bash
7777 needs to update resources in the AWS account, this can take a couple of minutes.
    ValidationError: Stack:arn:aws:cloudformation:ap-southeast-1:some-random-digits:stack/port7777/some-random-uuid is in ROLLBACK_COMPLETE state and can not be updated.
    Code: ValidationError
```

Retrying the 1st database give me this error

```bash
Retrieving the container security group.
    Error: Failed to retrieve the security group 7777-container-security-group-vpc-some-identifier
```

Retrying the 2nd database give me this error

```bash
7777 needs to update resources in the AWS account, this can take a couple of minutes.
    ValidationError: Stack:arn:aws:cloudformation:ap-southeast-1:some-identifier:stack/port7777/some-uuid is in ROLLBACK_COMPLETE state and can not be updated.
    Code: ValidationError
```

**Comment by ziming** [comment]
Hi,

These are the outputs with failure

CREATE_FAILED | 7777Cluster


Resource handler returned message: "Error occurred during operation 'CreateCluster SDK error: User: arn:aws:iam::SOME-DIGITS:user/777-user is not authorized to perform: ecs:TagResource on resource: arn:aws:ecs:ap-southeast-1:SOME-DIGITS:cluster/7777Cluster because no identity-based policy allows the ecs:TagResource action (Service: AmazonECS; Status Code: 400; Error Code: AccessDeniedException; Request ID: SOME-UUID; Proxy: null)'." (RequestToken: SOME-UUID, HandlerErrorCode: GeneralServiceException)


2nd status reason

CREATE_IN_PROGRESS | 7777BastionTaskExecutionRole

Encountered a permissions error performing a tagging operation, please add required tag permissions. See https://repost.aws/knowledge-center/cloudformation-tagging-permission-error for how to resolve. Resource handler returned message: "User: arn:aws:iam::SOME-DIGITS:user/777-user is not authorized to perform: iam:TagRole on resource: arn:aws:iam::SOME-DIGITs:role/port7777-7777BastionTaskExecutionRole-SOMERANDOMCHARS because no identity-based policy allows the iam:TagRole action (Service: Iam, Status Code: 403, Request ID: SOME-UUID)"

**Comment by mnapoli** [comment]
Ah there you go, the AWS credentials you are using to set up 7777 are missing the `ecs:TagResource` permissions unfortunately. Are you able to get those permissions added?

**Comment by ziming** [comment]
my policy is the same as what your documentation say, so can you update your documentation?

**Comment by mnapoli** [comment]
Ohh good point, this is a change in AWS, this is a new permission. It's in effect since a few months now: https://repost.aws/questions/QUgoPsMsP-Qn2u1GicAvcOJg/ecs-tagresource-update-your-iam-policies-by-march-29-2024

I added that in https://github.com/whilenull/7777-support/commit/28d6d110163817fd29a1cb8d424c494d64b4ff19

I'm marking this as resolved, please let me know if you still face issues!

**Comment by ziming** [comment]
I think you missed out on iam:TagRole

**Comment by mnapoli** [comment]
Thanks I added this too.
